/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Tools.KoneksiDB;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Aeiro
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
   KoneksiDB getCnn = new KoneksiDB();
    Connection _Cnn;
    
    String vid_user, vnama_user, vpass, vlev_user;
    String sqlselect;

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | FrMenu.MAXIMIZED_BOTH);
        disabledMenu();
        txtIDUser.requestFocus(true);
    }
    
     private void disabledMenu(){
        mnUser.setEnabled(false);
        Barang.setEnabled(false);
        Supplier.setEnabled(false);
        Karyawan.setEnabled(false);
        Kategori.setEnabled(false);
        Laporan.setEnabled(false);
    }
    
    private void enabledMenu(){
        mnUser.setEnabled(true);
        Barang.setEnabled(true);
        Supplier.setEnabled(true);
        Karyawan.setEnabled(true);
        Kategori.setEnabled(true);
        Laporan.setEnabled(true);
         
    }
    
    void userAdministrator(){
        mnUser.setVisible(true);
        Barang.setVisible(true);
        Supplier.setVisible(true);
        Karyawan.setVisible(true);
        Kategori.setVisible(true);
        Laporan.setVisible(true);
    }
    
    private void aksiLogin(){
        
        if(txtIDUser.getText().equals("") || txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ID. User dan Password harus diisi!");
        }else{
            vid_user = txtIDUser.getText();
            vpass = txtPassword.getText();
            try{
                _Cnn = null;
                _Cnn = getCnn.getConnection();
                sqlselect = "select * from tb_user where id_user='"+vid_user+"' "
                        + " and password=md5('"+vpass+"') ";
                Statement stat = _Cnn.createStatement();
                ResultSet res = stat.executeQuery(sqlselect);
                if(res.first()){
                    vnama_user = res.getString("nama_user");
                    panelLogin.setVisible(false);
                    enabledMenu();
                }else{
                    JOptionPane.showMessageDialog(this, "ID. User dan Password salah!");
                }
                
            }catch(SQLException se){
                JOptionPane.showMessageDialog(this, "Error method aksilogin() : " + se);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelMenu = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        aasd = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnUser = new javax.swing.JMenu();
        MnUser = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        Barang = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        Supplier = new javax.swing.JMenu();
        mnSupplier = new javax.swing.JMenuItem();
        Karyawan = new javax.swing.JMenu();
        mnKaryawan = new javax.swing.JMenuItem();
        mnShift = new javax.swing.JMenuItem();
        Kategori = new javax.swing.JMenu();
        mnKategori = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        mnCetakLaporanBarang = new javax.swing.JMenuItem();
        mnCetakLaporanSupplier = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel7.setFont(new java.awt.Font("Humanst521 BT", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sistem Inventory Barang");

        jLabel8.setFont(new java.awt.Font("Humanst521 BT", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CV. Elektronik Berjaya");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(602, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panelMenu.setBackground(new java.awt.Color(0, 92, 44));

        panelLogin.setBackground(new java.awt.Color(0, 102, 51));

        aasd.setFont(new java.awt.Font("Humanst521 BT", 1, 18)); // NOI18N
        aasd.setForeground(new java.awt.Color(255, 255, 255));
        aasd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aasd.setText("Login User");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_User_96px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Humanst521 BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID. User");

        txtIDUser.setBackground(new java.awt.Color(0, 92, 44));
        txtIDUser.setForeground(new java.awt.Color(255, 255, 255));
        txtIDUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDUserActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Humanst521 BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :");

        txtPassword.setBackground(new java.awt.Color(0, 92, 44));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDUser)
                    .addComponent(txtPassword)
                    .addComponent(aasd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addComponent(aasd)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(849, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_User_48px.png"))); // NOI18N
        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });

        MnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_User_48px.png"))); // NOI18N
        MnUser.setText("User");
        MnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUserActionPerformed(evt);
            }
        });
        mnUser.add(MnUser);

        mnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Sign_Out_48px.png"))); // NOI18N
        mnKeluar.setText("Sign Out");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnUser.add(mnKeluar);

        jMenuBar1.add(mnUser);

        Barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Product_40px.png"))); // NOI18N
        Barang.setText("Data Barang");
        Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarangMouseClicked(evt);
            }
        });
        Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangActionPerformed(evt);
            }
        });

        mnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Product_40px.png"))); // NOI18N
        mnBarang.setText("Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        Barang.add(mnBarang);

        jMenuBar1.add(Barang);

        Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Supplier_48px.png"))); // NOI18N
        Supplier.setText("Data Supplier");
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });

        mnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Supplier_48px.png"))); // NOI18N
        mnSupplier.setText("Supplier");
        mnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSupplierActionPerformed(evt);
            }
        });
        Supplier.add(mnSupplier);

        jMenuBar1.add(Supplier);

        Karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Member_48px.png"))); // NOI18N
        Karyawan.setText("Data Karyawan");
        Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaryawanActionPerformed(evt);
            }
        });

        mnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Member_48px.png"))); // NOI18N
        mnKaryawan.setText("Karyawan");
        mnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaryawanActionPerformed(evt);
            }
        });
        Karyawan.add(mnKaryawan);

        mnShift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Schedule_40px.png"))); // NOI18N
        mnShift.setText("Shift");
        mnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnShiftActionPerformed(evt);
            }
        });
        Karyawan.add(mnShift);

        jMenuBar1.add(Karyawan);

        Kategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Category_48px_2.png"))); // NOI18N
        Kategori.setText("Data Kategori");
        Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriActionPerformed(evt);
            }
        });

        mnKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Categorize_30px.png"))); // NOI18N
        mnKategori.setText("Kategori");
        mnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKategoriActionPerformed(evt);
            }
        });
        Kategori.add(mnKategori);

        jMenuBar1.add(Kategori);

        Laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Document_48px.png"))); // NOI18N
        Laporan.setText("Laporan");

        mnCetakLaporanBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Print_48px.png"))); // NOI18N
        mnCetakLaporanBarang.setText("Laporan Barang");
        mnCetakLaporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCetakLaporanBarangActionPerformed(evt);
            }
        });
        Laporan.add(mnCetakLaporanBarang);

        mnCetakLaporanSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Print_48px.png"))); // NOI18N
        mnCetakLaporanSupplier.setText("Laporan Supplier");
        mnCetakLaporanSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCetakLaporanSupplierActionPerformed(evt);
            }
        });
        Laporan.add(mnCetakLaporanSupplier);

        jMenuBar1.add(Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCetakLaporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCetakLaporanBarangActionPerformed
        // TODO add your handling code here:
        IfrLapBarang n = new IfrLapBarang();
        n.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mnCetakLaporanBarangActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah anda akan keluar dari sistem?","Informasi",
                JOptionPane.YES_NO_OPTION);
        if(jawab == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
            IfrUser fr = new IfrUser();
            panelMenu.add(fr);
            fr.setVisible(true);
    }//GEN-LAST:event_mnUserActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        aksiLogin();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtIDUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        aksiLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangActionPerformed
       
    }//GEN-LAST:event_BarangActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierActionPerformed

    private void KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KaryawanActionPerformed

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriActionPerformed

    private void BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMouseClicked
       
    }//GEN-LAST:event_BarangMouseClicked

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        // TODO add your handling code here:
        IfrBarang n = new IfrBarang();
        n.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSupplierActionPerformed
        // TODO add your handling code here:
        IfrSupplier n = new IfrSupplier();
        n.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mnSupplierActionPerformed

    private void mnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaryawanActionPerformed
        // TODO add your handling code here:
        IfrKaryawan n = new IfrKaryawan();
        n.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mnKaryawanActionPerformed

    private void mnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnShiftActionPerformed
        // TODO add your handling code here:
        IfrShift n = new IfrShift();
        n.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mnShiftActionPerformed

    private void mnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKategoriActionPerformed
        // TODO add your handling code here:
        IfrKategori n = new IfrKategori();
        n.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_mnKategoriActionPerformed

    private void mnCetakLaporanSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCetakLaporanSupplierActionPerformed
        // TODO add your handling code here:
        IfrLapSupplier n = new IfrLapSupplier();
        n.setVisible(true);
        this.setVisible(true);
        
    }//GEN-LAST:event_mnCetakLaporanSupplierActionPerformed

    private void MnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUserActionPerformed
        // TODO add your handling code here:
        IfrUser n = new IfrUser();
        n.setVisible(true);
        this.setVisible(true);
        
    }//GEN-LAST:event_MnUserActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Barang;
    private javax.swing.JMenu Karyawan;
    private javax.swing.JMenu Kategori;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem MnUser;
    private javax.swing.JMenu Supplier;
    private javax.swing.JLabel aasd;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenuItem mnCetakLaporanBarang;
    private javax.swing.JMenuItem mnCetakLaporanSupplier;
    private javax.swing.JMenuItem mnKaryawan;
    private javax.swing.JMenuItem mnKategori;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnShift;
    private javax.swing.JMenuItem mnSupplier;
    private javax.swing.JMenu mnUser;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtIDUser;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
